service: ev-charger-server

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  stage: ${opt:stage, "stage"}
  environment:
    NODE_ENV: ${self:provider.stage}
    AWS_DEPLOY_REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

functions:
  api:
    handler: index.handler
    description: main api server
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-plugin-typescript
  - serverless-offline
